### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by yuvraj-yadav** [yuvraj-yadav/Humpback#10]
Need help in this

`def selected(e):
            details=dataAdapter.showPersonDetails(e,subBandobastList.get())`

whats happeing

**Comment by yyuvraj54** [comment]
hello

**Comment by yuvraj-yadav** [comment]
hi

**Comment by yuvraj-yadav** [comment]
please tell the answer??

**Comment by yyuvraj54** [comment]
oo its simple bro

**Comment by yyuvraj54** [comment]
this code helps to get the name of selected item in listbox

**Comment by yuvraj-yadav** [comment]
ooo ok thanks

**Comment by yyuvraj54** [comment]
> Need help in this
> 
> `def selected(e): details=dataAdapter.showPersonDetails(e,subBandobastList.get())`
> 
> whats happeing

now close this issue

**Comment by yuvraj-yadav** [comment]
ok i am closing this issue
