### ISSUE TITLE
add the main code to it 

### ISSUE THREAD

**Issue by yuvraj-yadav** [yuvraj-yadav/Humpback#8]
crash script must be added in root dir 
with default path

`class PMS_Window(CTk):  
  
    def __init__(self, *args, **kwargs):  
          
        CTk.__init__(self, *args, **kwargs)  
        
        container = customtkinter.CTkFrame(self)  
        container.pack(side="top", fill="both", expand = True)  
        container.grid_rowconfigure(0, weight=1)  
        container.grid_columnconfigure(0, weight=1)  
  
        self.frames = {}  
  
        for F in (Agreement_Licence_Page, Login_Page,CreateBandobastArea):  
            frame = F(container, self)  
            self.frames[F] = frame  
            frame.grid(row=0, column=0, sticky="nsew")  
        self.show_frame(Agreement_Licence_Page)  
  
    def show_frame(self, cont):  
        frame = self.frames[cont]  
        frame.tkraise()  `

**Comment by yyuvraj54** [comment]
ok. ye to easy h

**Comment by yyuvraj54** [comment]
ok its solved
